import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import net from 'node:net';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import {chromium} from 'playwright-core';
const root=path.resolve(import.meta.dirname,'../..'), evidence=path.resolve(process.argv[2] || path.join(root,'target/qualification'));
const runId=crypto.randomUUID(),dir=path.join(evidence,'observations','hosts-'+runId);fs.mkdirSync(dir,{recursive:true});
const requests=[];let worker,workerExit,browser;
const server=http.createServer(async(req,res)=>{requests.push({method:req.method,target:req.url});res.setHeader('Access-Control-Allow-Origin','*');const u=new URL(req.url,'http://localhost');if(u.pathname==='/ready'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({run_id:runId}));return;}if(u.pathname==='/redirect'){res.writeHead(302,{Location:'/followed'});res.end();return;}if(u.pathname==='/echo'){const chunks=[];for await(const c of req)chunks.push(c);res.setHeader('Content-Type','application/json');res.end(Buffer.concat(chunks));return;}if(u.pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<title>OpenAPI Rust qualification</title>');return;}const p=path.resolve(root,'.'+u.pathname);if(!p.startsWith(root+'/')){res.writeHead(404);res.end();return;}try{res.setHeader('Content-Type',p.endsWith('.wasm')?'application/wasm':p.endsWith('.js')||p.endsWith('.mjs')?'text/javascript':'application/json');res.end(fs.readFileSync(p));}catch{res.writeHead(404);res.end();}});
await new Promise((resolve,reject)=>server.once('error',reject).listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
let outcome={run_id:runId,base,started_at:new Date().toISOString(),requests};
try{
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE || undefined,headless:true});const page=await browser.newPage();const messages=[];page.on('pageerror',e=>messages.push(String(e)));await page.goto(base);
 outcome.browser=await page.evaluate(async({base,runId})=>{const t=performance.now();const api=await import(base+'/qualification/bridge/generated/oac_host_qualification.js');await api.default();const startup=performance.now()-t;const {runHost,hostBench}=await import(base+'/qualification/host/probes.mjs');return {...await runHost(api,base,'browser',runId),startup_ms:startup,benchmarks:await hostBench(api,base)};},{base,runId});outcome.browser.version=browser.version();outcome.browser.messages=messages;await browser.close();browser=null;
 const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
 const config={name:'oac-local-qualification',main:path.join(root,'qualification/host/worker.mjs'),compatibility_date:'2026-10-08',compatibility_flags:[],vars:{PROBE_BASE:base,RUN_ID:runId}};fs.writeFileSync(path.join(dir,'wrangler.json'),JSON.stringify(config,null,2));
 const wrangler=path.join(import.meta.dirname,'node_modules/wrangler/bin/wrangler.js');const log=fs.openSync(path.join(dir,'workerd.log'),'w');worker=spawn(process.execPath,[wrangler,'dev','--local','--config',path.join(dir,'wrangler.json'),'--port',String(port),'--ip','127.0.0.1','--persist-to',path.join(dir,'state')],{cwd:dir,env:{...process.env,WRANGLER_SEND_METRICS:'false',WRANGLER_LOG_PATH:path.join(dir,'wrangler.log'),CI:'1'},stdio:['ignore',log,log]});workerExit=new Promise(r=>worker.once('exit',(code,signal)=>r({code,signal})));outcome.worker_pid=worker.pid;
 let ready=false;for(let i=0;i<200;i++){if(worker.exitCode!==null)throw Error('worker exited before readiness');try{const r=await fetch(`http://127.0.0.1:${port}/ready`,{signal:AbortSignal.timeout(500)});const j=await r.json();if(j.run_id===runId){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}if(!ready)throw Error('fresh workerd readiness not observed');
 outcome.worker_ready={run_id:runId,port};outcome.workerd=await(await fetch(`http://127.0.0.1:${port}/run`,{signal:AbortSignal.timeout(15000)})).json();outcome.passed=outcome.browser.passed&&outcome.workerd.passed&&!requests.some(r=>r.target==='/followed');
}catch(e){outcome.error=String(e);outcome.stack=e.stack;outcome.passed=false;}
finally{if(browser)await browser.close();if(worker){worker.kill('SIGTERM');outcome.worker_exit=await Promise.race([workerExit,new Promise(r=>setTimeout(()=>{worker.kill('SIGKILL');r({forced:true});},5000))]);}server.closeAllConnections();await new Promise(r=>server.close(r));outcome.server_closed=true;outcome.finished_at=new Date().toISOString();fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify(outcome,null,2));console.log(JSON.stringify({dir,passed:outcome.passed,error:outcome.error,browser:outcome.browser?.passed,workerd:outcome.workerd?.passed}));}
if(!outcome.passed)process.exitCode=1;
