use crate::{
    Code, Diagnostic, DiagnosticReason, LimitKind, Location, NumericReason, NumericTarget,
};
use serde::{
    Deserializer,
    de::{DeserializeSeed, MapAccess, SeqAccess, Visitor},
};
use serde_json::value::RawValue;
use std::{
    collections::HashMap,
    fmt,
    ops::Range,
    sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
    },
};

/// Resource admission limits. Defaults are part of the qualified profile.
#[derive(Clone, Debug)]
#[allow(missing_docs)]
pub struct Limits {
    pub document_bytes: usize,
    pub depth: usize,
    pub nodes: usize,
    pub operations: usize,
    pub reference_steps: usize,
    pub body_bytes: usize,
    pub target_bytes: usize,
    pub headers: usize,
    pub number_conversion_chars: usize,
    pub cached_operations: usize,
}
impl Default for Limits {
    fn default() -> Self {
        Self {
            document_bytes: 8 * 1024 * 1024,
            depth: 128,
            nodes: 500_000,
            operations: 20_000,
            reference_steps: 128,
            body_bytes: 4 * 1024 * 1024,
            target_bytes: 65_536,
            headers: 256,
            number_conversion_chars: 256,
            cached_operations: 1024,
        }
    }
}

/// Parse failure retaining admitted original bytes, including invalid UTF-8.
/// Over-byte-limit inputs are not copied; `source` is empty for that admission failure.
#[derive(Clone)]
pub struct ParseFailure {
    /// Failure category and source locations.
    pub diagnostic: Diagnostic,
    /// Exact admitted bytes; empty when the input exceeds the byte admission limit.
    pub source: Arc<[u8]>,
}
impl fmt::Debug for ParseFailure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ParseFailure")
            .field("diagnostic", &self.diagnostic)
            .field("bytes", &self.source.len())
            .finish()
    }
}
impl fmt::Display for ParseFailure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.diagnostic.fmt(f)
    }
}
impl std::error::Error for ParseFailure {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        Some(&self.diagnostic)
    }
}

/// Origin of the immutable JSON bytes indexed by an owner.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SourceOrigin {
    /// Bytes supplied to parse by the caller (including received response bytes).
    Authored,
    /// JSON bytes generated by the supported typed ordinary-value helper.
    Constructed,
}
/// Identity of a source within this process or Wasm instance, not a persistent/global ID.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SourceContext {
    /// Distinguishes parse/construction owners even when their bytes are identical.
    pub id: usize,
    /// Whether indexed bytes were supplied or constructed by this library.
    pub origin: SourceOrigin,
}
static NEXT_SOURCE: AtomicUsize = AtomicUsize::new(1);

/// An immutable, exact JSON owner. Clones share bytes and the flat index.
#[derive(Clone, Debug)]
pub struct ExactJson(pub(crate) Value);
/// An independently owned handle to an authored JSON value.
#[derive(Clone)]
pub struct Value {
    store: Arc<Store>,
    id: usize,
}
impl fmt::Debug for Value {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Value")
            .field("kind", &self.kind())
            .field("range", &self.node().span)
            .finish()
    }
}
/// JSON value category, without conversion or default insertion.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[allow(missing_docs)]
pub enum ValueKind {
    Null,
    Boolean,
    Number,
    String,
    Array,
    Object,
}
struct Member {
    name: Arc<str>,
    value: usize,
    key: Range<usize>,
}
enum Kind {
    Null,
    Bool(bool),
    Number,
    String(String),
    Array(Vec<usize>),
    Object(Vec<Member>, HashMap<Arc<str>, usize>),
}
struct Node {
    span: Range<usize>,
    parent: Option<usize>,
    segment: Arc<str>,
    kind: Kind,
}
struct Store {
    source: Arc<str>,
    context: SourceContext,
    nodes: Vec<Node>,
    limits: Limits,
}
static LIVE: AtomicUsize = AtomicUsize::new(0);
impl Drop for Store {
    fn drop(&mut self) {
        LIVE.fetch_sub(1, Ordering::Relaxed);
    }
}
/// Number of live JSON backing owners in this process; reserved allocator pages are excluded.
pub fn live_json_owners() -> usize {
    LIVE.load(Ordering::Relaxed)
}

// This visitor borrows child tokens from serde_json; JSON grammar belongs to the dependency.
struct Entries<'a>(Vec<(String, &'a RawValue)>);
struct ObjectSeed(usize);
impl<'de> DeserializeSeed<'de> for ObjectSeed {
    type Value = Entries<'de>;
    fn deserialize<D: Deserializer<'de>>(self, d: D) -> Result<Self::Value, D::Error> {
        struct V(usize);
        impl<'de> Visitor<'de> for V {
            type Value = Entries<'de>;
            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_str("bounded object")
            }
            fn visit_map<M: MapAccess<'de>>(self, mut m: M) -> Result<Self::Value, M::Error> {
                let mut v = Vec::new();
                while let Some(entry) = m.next_entry::<String, &'de RawValue>()? {
                    if v.len() >= self.0 {
                        return Err(serde::de::Error::custom("node limit"));
                    }
                    v.push(entry);
                }
                Ok(Entries(v))
            }
        }
        d.deserialize_map(V(self.0))
    }
}
struct ArraySeed(usize);
impl<'de> DeserializeSeed<'de> for ArraySeed {
    type Value = Vec<&'de RawValue>;
    fn deserialize<D: Deserializer<'de>>(self, d: D) -> Result<Self::Value, D::Error> {
        struct V(usize);
        impl<'de> Visitor<'de> for V {
            type Value = Vec<&'de RawValue>;
            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_str("bounded array")
            }
            fn visit_seq<M: SeqAccess<'de>>(self, mut m: M) -> Result<Self::Value, M::Error> {
                let mut v = Vec::new();
                while let Some(value) = m.next_element::<&'de RawValue>()? {
                    if v.len() >= self.0 {
                        return Err(serde::de::Error::custom("node limit"));
                    }
                    v.push(value);
                }
                Ok(v)
            }
        }
        d.deserialize_seq(V(self.0))
    }
}
fn parse_error(e: serde_json::Error, offset: usize) -> Diagnostic {
    let code = if e.to_string().contains("node limit") {
        Code::Limit
    } else if e.to_string().contains("surrogate")
        || e.to_string().contains("leading surrogate")
        || e.to_string().contains("end of hex escape")
    {
        Code::UnsupportedString
    } else {
        Code::InvalidJson
    };
    Diagnostic::new(code).at(Location {
        start: offset,
        end: offset,
        pointer: String::new(),
    })
}
fn depth_guard(
    bytes: &[u8],
    limit: usize,
    cancellation: &crate::Cancellation,
) -> Result<(), Diagnostic> {
    let (mut depth, mut string, mut escaped) = (0usize, false, false);
    for (i, &b) in bytes.iter().enumerate() {
        if i % 4096 == 0 {
            cancellation.check()?;
        }
        if string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                string = false;
            }
        } else {
            match b {
                b'"' => string = true,
                b'[' | b'{' => {
                    depth += 1;
                    if depth > limit.min(128) {
                        return Err(Diagnostic::limited(LimitKind::Depth, limit.min(128), depth)
                            .at(Location {
                                start: i,
                                end: i + 1,
                                pointer: String::new(),
                            }));
                    }
                }
                b']' | b'}' => depth = depth.saturating_sub(1),
                _ => {}
            }
        }
    }
    Ok(())
}
// Capacity planning over already grammar-validated JSON. This does not interpret values;
// serde_json remains the grammar authority. Count tokens while skipping quoted strings,
// and exclude strings followed by ':' (member names). Exact reservation avoids repeated
// large Vec reallocations and their substantial macOS allocator cache footprint.
fn validated_node_count(text: &str) -> usize {
    let b = text.as_bytes();
    let (mut i, mut count) = (0, 0);
    while i < b.len() {
        match b[i] {
            b'{' | b'[' => {
                count += 1;
                i += 1;
            }
            b'"' => {
                i += 1;
                let mut escaped = false;
                while i < b.len() {
                    let c = b[i];
                    i += 1;
                    if escaped {
                        escaped = false;
                    } else if c == b'\\' {
                        escaped = true;
                    } else if c == b'"' {
                        break;
                    }
                }
                let mut next = i;
                while next < b.len() && b[next].is_ascii_whitespace() {
                    next += 1;
                }
                if b.get(next) != Some(&b':') {
                    count += 1;
                }
            }
            b'}' | b']' | b':' | b',' | b' ' | b'\t' | b'\n' | b'\r' => i += 1,
            _ => {
                count += 1;
                while i < b.len() && !b[i].is_ascii_whitespace() && !b"[]{}:,".contains(&b[i]) {
                    i += 1;
                }
            }
        }
    }
    count
}
impl ExactJson {
    /// Validate and index exact UTF-8 JSON. Duplicate decoded keys are rejected.
    /// String values containing unpaired UTF-16 surrogate escapes return UnsupportedString.
    pub fn parse(bytes: impl AsRef<[u8]>, limits: Limits) -> Result<Self, ParseFailure> {
        Self::parse_with_cancellation(bytes, limits, &crate::Cancellation::default())
    }
    /// Parse with cancellation checkpoints during owned indexing and admission.
    pub fn parse_with_cancellation(
        bytes: impl AsRef<[u8]>,
        limits: Limits,
        cancellation: &crate::Cancellation,
    ) -> Result<Self, ParseFailure> {
        Self::parse_in_origin(bytes.as_ref(), limits, cancellation, SourceOrigin::Authored)
    }
    pub(crate) fn parse_in_origin(
        bytes: &[u8],
        limits: Limits,
        cancellation: &crate::Cancellation,
        origin: SourceOrigin,
    ) -> Result<Self, ParseFailure> {
        let id = NEXT_SOURCE
            .try_update(Ordering::Relaxed, Ordering::Relaxed, |n| n.checked_add(1))
            .map_err(|_| ParseFailure {
                diagnostic: Diagnostic::new(Code::Limit).setting("source_identities"),
                source: Arc::from([]),
            })?;
        let context = SourceContext { id, origin };
        let admitted = bytes.len() <= limits.document_bytes;
        let parsed = (|| {
            cancellation.check()?;
            if bytes.len() > limits.document_bytes {
                return Err(Diagnostic::limited(
                    LimitKind::DocumentBytes,
                    limits.document_bytes,
                    bytes.len(),
                ));
            }
            depth_guard(bytes, limits.depth, cancellation)?;
            let text = std::str::from_utf8(bytes).map_err(|e| {
                Diagnostic::new(Code::InvalidUtf8).at(Location {
                    start: e.valid_up_to(),
                    end: e.valid_up_to() + e.error_len().unwrap_or(0),
                    pointer: String::new(),
                })
            })?;
            let root: &RawValue = serde_json::from_str(text).map_err(|e| {
                let offset = text
                    .split_inclusive('\n')
                    .take(e.line().saturating_sub(1))
                    .map(str::len)
                    .sum::<usize>()
                    + e.column().saturating_sub(1);
                parse_error(e, offset.min(text.len()))
            })?;
            let offset = |v: &RawValue| {
                let a = v.get().as_ptr() as usize - text.as_ptr() as usize;
                a..a + v.get().len()
            };
            let node_count = validated_node_count(root.get());
            if node_count > limits.nodes {
                return Err(Diagnostic::limited(
                    LimitKind::Nodes,
                    limits.nodes,
                    node_count,
                ));
            }
            let mut nodes = Vec::with_capacity(node_count);
            nodes.push(Node {
                span: offset(root),
                parent: None,
                segment: Arc::from(""),
                kind: Kind::Null,
            });
            let mut queue = Vec::with_capacity(node_count);
            queue.push(root);
            let mut cursor = 0;
            while cursor < queue.len() {
                cancellation.check()?;
                if queue.len() > limits.nodes {
                    return Err(Diagnostic::new(Code::Limit));
                }
                let raw = queue[cursor];
                let s = raw.get();
                let kind = match s.as_bytes()[0] {
                    b'{' => {
                        let entries: Entries = ObjectSeed(limits.nodes.saturating_sub(nodes.len()))
                            .deserialize(&mut serde_json::Deserializer::from_str(s))
                            .map_err(|e| parse_error(e, nodes[cursor].span.start))?;
                        if entries.0.len() > limits.nodes.saturating_sub(nodes.len()) {
                            return Err(Diagnostic::new(Code::Limit));
                        }
                        let mut members: Vec<Member> = Vec::with_capacity(entries.0.len());
                        let mut lookup = HashMap::with_capacity(entries.0.len());
                        let mut last = nodes[cursor].span.start + 1;
                        for (name, value) in entries.0 {
                            let span = offset(value);
                            // Locate the already-validated member key, without interpreting JSON grammar.
                            let start = last
                                + text.as_bytes()[last..span.start]
                                    .iter()
                                    .position(|b| *b == b'"')
                                    .unwrap_or(0);
                            let (mut end, mut escaped) = (start + 1, false);
                            while end < span.start {
                                let b = text.as_bytes()[end];
                                end += 1;
                                if escaped {
                                    escaped = false;
                                } else if b == b'\\' {
                                    escaped = true;
                                } else if b == b'"' {
                                    break;
                                }
                            }
                            if let Some(&previous) = lookup.get(name.as_str()) {
                                let old: &Member = &members[previous];
                                let mut error =
                                    Diagnostic::new(Code::DuplicateMember).at(Location {
                                        start,
                                        end,
                                        pointer: String::new(),
                                    });
                                error.related.push(Location {
                                    start: old.key.start,
                                    end: old.key.end,
                                    pointer: String::new(),
                                });
                                return Err(error);
                            }
                            let name: Arc<str> = name.into();
                            let id = nodes.len();
                            nodes.push(Node {
                                span: span.clone(),
                                parent: Some(cursor),
                                segment: name.clone(),
                                kind: Kind::Null,
                            });
                            queue.push(value);
                            lookup.insert(name.clone(), members.len());
                            members.push(Member {
                                name,
                                value: id,
                                key: start..end,
                            });
                            last = span.end;
                        }
                        Kind::Object(members, lookup)
                    }
                    b'[' => {
                        let children: Vec<&RawValue> =
                            ArraySeed(limits.nodes.saturating_sub(nodes.len()))
                                .deserialize(&mut serde_json::Deserializer::from_str(s))
                                .map_err(|e| parse_error(e, nodes[cursor].span.start))?;
                        if children.len() > limits.nodes.saturating_sub(nodes.len()) {
                            return Err(Diagnostic::new(Code::Limit));
                        }
                        let mut ids = Vec::with_capacity(children.len());
                        for (i, v) in children.into_iter().enumerate() {
                            ids.push(nodes.len());
                            nodes.push(Node {
                                span: offset(v),
                                parent: Some(cursor),
                                segment: Arc::from(i.to_string()),
                                kind: Kind::Null,
                            });
                            queue.push(v);
                        }
                        Kind::Array(ids)
                    }
                    b'"' => Kind::String(
                        serde_json::from_str(s)
                            .map_err(|e| parse_error(e, nodes[cursor].span.start))?,
                    ),
                    b't' => Kind::Bool(true),
                    b'f' => Kind::Bool(false),
                    b'n' => Kind::Null,
                    _ => Kind::Number,
                };
                nodes[cursor].kind = kind;
                cursor += 1;
            }
            debug_assert_eq!(nodes.len(), node_count);
            LIVE.fetch_add(1, Ordering::Relaxed);
            Ok(Self(Value {
                store: Arc::new(Store {
                    source: Arc::from(text),
                    context,
                    nodes,
                    limits,
                }),
                id: 0,
            }))
        })();
        parsed.map_err(|diagnostic| ParseFailure {
            diagnostic: diagnostic.sourced(context),
            source: if admitted {
                Arc::from(bytes)
            } else {
                Arc::from([])
            },
        })
    }
    /// The independently owned root value.
    pub fn root(&self) -> Value {
        self.0.clone()
    }
    /// Exact source including leading/trailing whitespace.
    pub fn source(&self) -> &str {
        &self.0.store.source
    }
    /// Accounted retained source/index storage (not allocator RSS).
    pub fn retained_bytes(&self) -> usize {
        self.0.retained_bytes()
    }
}
impl Value {
    fn node(&self) -> &Node {
        &self.store.nodes[self.id]
    }
    pub(crate) fn identity(&self) -> usize {
        self.id
    }
    /// Exact original JSON token or subtree, without conversion.
    pub fn raw(&self) -> &str {
        &self.store.source[self.node().span.clone()]
    }
    /// Type of this JSON value.
    pub fn kind(&self) -> ValueKind {
        match self.node().kind {
            Kind::Null => ValueKind::Null,
            Kind::Bool(_) => ValueKind::Boolean,
            Kind::Number => ValueKind::Number,
            Kind::String(_) => ValueKind::String,
            Kind::Array(_) => ValueKind::Array,
            Kind::Object(..) => ValueKind::Object,
        }
    }
    /// Decoded Unicode scalar string, when this is a string.
    pub fn as_str(&self) -> Option<&str> {
        if let Kind::String(s) = &self.node().kind {
            Some(s)
        } else {
            None
        }
    }
    /// Boolean value, with absent/wrong-kind distinct from false.
    pub fn as_bool(&self) -> Option<bool> {
        if let Kind::Bool(b) = self.node().kind {
            Some(b)
        } else {
            None
        }
    }
    /// Exact number token and fallible numeric conveniences.
    pub fn number(&self) -> Option<Number<'_>> {
        (self.kind() == ValueKind::Number).then_some(Number {
            token: self.raw(),
            limit: self.store.limits.number_conversion_chars,
            value: self,
        })
    }
    /// Object lookup; missing and explicit null remain distinct.
    pub fn get(&self, name: &str) -> Option<Self> {
        if let Kind::Object(m, index) = &self.node().kind {
            index.get(name).map(|&i| Self {
                store: self.store.clone(),
                id: m[i].value,
            })
        } else {
            None
        }
    }
    /// Array lookup.
    pub fn at(&self, index: usize) -> Option<Self> {
        if let Kind::Array(a) = &self.node().kind {
            a.get(index).map(|&id| Self {
                store: self.store.clone(),
                id,
            })
        } else {
            None
        }
    }
    /// Authored object member order with independently owned child handles.
    pub fn members(&self) -> Option<impl ExactSizeIterator<Item = (&str, Self)> + '_> {
        if let Kind::Object(m, ..) = &self.node().kind {
            Some(m.iter().map(|m| {
                (
                    m.name.as_ref(),
                    Self {
                        store: self.store.clone(),
                        id: m.value,
                    },
                )
            }))
        } else {
            None
        }
    }
    /// Authored array element order.
    pub fn elements(&self) -> Option<impl ExactSizeIterator<Item = Self> + '_> {
        if let Kind::Array(a) = &self.node().kind {
            Some(a.iter().map(|&id| Self {
                store: self.store.clone(),
                id,
            }))
        } else {
            None
        }
    }
    /// Source range and authored JSON Pointer.
    pub fn location(&self) -> Location {
        let mut id = self.id;
        let mut segments = vec![];
        while let Some(parent) = self.store.nodes[id].parent {
            segments.push(
                self.store.nodes[id]
                    .segment
                    .replace('~', "~0")
                    .replace('/', "~1"),
            );
            id = parent;
        }
        segments.reverse();
        Location {
            start: self.node().span.start,
            end: self.node().span.end,
            pointer: if segments.is_empty() {
                String::new()
            } else {
                format!("/{}", segments.join("/"))
            },
        }
    }
    /// Exact source owner and authored/constructed origin of this value's ranges.
    pub fn source_context(&self) -> SourceContext {
        self.store.context
    }
    /// Resolve an RFC6901 string-form pointer within this value; no URI decoding here.
    pub fn pointer(&self, pointer: &str) -> Result<Self, Diagnostic> {
        if pointer.len() > self.store.limits.document_bytes
            || pointer.bytes().filter(|b| *b == b'/').count() > self.store.limits.depth
        {
            return Err(self.error(Code::Limit));
        }
        if pointer.is_empty() {
            return Ok(self.clone());
        }
        if !pointer.starts_with('/') {
            return Err(self.error(Code::InvalidPointer));
        }
        let mut current = self.clone();
        for token in pointer[1..].split('/') {
            let mut decoded = String::new();
            let mut chars = token.chars();
            while let Some(c) = chars.next() {
                if c == '~' {
                    decoded.push(match chars.next() {
                        Some('0') => '~',
                        Some('1') => '/',
                        _ => return Err(self.error(Code::InvalidPointer)),
                    });
                } else {
                    decoded.push(c);
                }
            }
            current = match current.kind() {
                ValueKind::Object => current.get(&decoded),
                ValueKind::Array => {
                    if decoded.is_empty()
                        || (decoded.starts_with('0') && decoded.len() > 1)
                        || !decoded.bytes().all(|c| c.is_ascii_digit())
                    {
                        return Err(current.error(Code::InvalidPointer));
                    }
                    current.at(decoded
                        .parse::<usize>()
                        .map_err(|_| current.error(Code::InvalidPointer))?)
                }
                _ => None,
            }
            .ok_or_else(|| current.error(Code::MissingReference))?;
        }
        Ok(current)
    }
    pub(crate) fn error(&self, code: Code) -> Diagnostic {
        Diagnostic::new(code)
            .at(self.location())
            .sourced(self.source_context())
    }
    /// Retained storage attributable to the shared owner, counted once per owner.
    pub fn retained_bytes(&self) -> usize {
        let mut bytes =
            self.store.source.len() + self.store.nodes.capacity() * std::mem::size_of::<Node>();
        for n in &self.store.nodes {
            bytes += n.segment.len();
            match &n.kind {
                Kind::String(s) => bytes += s.capacity(),
                Kind::Array(a) => bytes += a.capacity() * std::mem::size_of::<usize>(),
                Kind::Object(m, h) => {
                    bytes += m.capacity() * std::mem::size_of::<Member>()
                        + h.capacity() * (std::mem::size_of::<(Arc<str>, usize)>() + 1);
                    bytes += m.iter().map(|m| m.name.len()).sum::<usize>();
                }
                _ => {}
            }
        }
        bytes
    }
}
/// Exact number view; conversion never changes the stored lexeme.
#[derive(Clone, Copy)]
pub struct Number<'a> {
    token: &'a str,
    limit: usize,
    value: &'a Value,
}
impl fmt::Debug for Number<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Number([redacted])")
    }
}
impl<'a> Number<'a> {
    /// Authored JSON number lexeme.
    pub fn token(self) -> &'a str {
        self.token
    }
    /// Checked integer lexical conversion. Fractions/exponents are explicit refusals.
    pub fn to_i64(self) -> Result<i64, Diagnostic> {
        self.admit(NumericTarget::I64)?;
        self.token
            .parse()
            .map_err(|_| self.refusal(NumericTarget::I64, NumericReason::SignedRange))
    }
    /// Checked unsigned integer lexical conversion.
    pub fn to_u64(self) -> Result<u64, Diagnostic> {
        self.admit(NumericTarget::U64)?;
        self.token
            .parse()
            .map_err(|_| self.refusal(NumericTarget::U64, NumericReason::UnsignedRange))
    }
    /// Exact binary64 conversion for integer lexemes fitting i64. Fractions/exponents,
    /// integers outside i64 (even exact powers of two), and rounding are distinct refusals.
    pub fn to_f64_exact(self) -> Result<f64, Diagnostic> {
        self.admit(NumericTarget::F64Exact)?;
        let n: i64 = self
            .token
            .parse()
            .map_err(|_| self.refusal(NumericTarget::F64Exact, NumericReason::SignedRange))?;
        let f = if self.token == "-0" { -0.0 } else { n as f64 };
        if f as i128 == n as i128 {
            Ok(f)
        } else {
            Err(self.refusal(NumericTarget::F64Exact, NumericReason::PrecisionLoss))
        }
    }
    fn refusal(self, target: NumericTarget, reason: NumericReason) -> Diagnostic {
        self.value
            .error(Code::NumericConversion)
            .reasoned(DiagnosticReason::Numeric { target, reason })
    }
    fn admit(self, target: NumericTarget) -> Result<(), Diagnostic> {
        if self.token.len() > self.limit {
            return Err(Diagnostic::limited(
                LimitKind::NumberCharacters,
                self.limit,
                self.token.len(),
            )
            .at(self.value.location())
            .sourced(self.value.source_context()));
        }
        if self.token.contains(['.', 'e', 'E']) {
            return Err(self.refusal(target, NumericReason::UnsupportedLexicalForm));
        }
        Ok(())
    }
}
